---
title: "GeoJSON to SVG"
author: "André Ourednik"
---

# Info

This is an R utility for batch converting geoJSON files to SVG.

# Libraries

```{r}
# installation of sf needs gdal. Envetually, you need to run system("hombrew install gdal") before. 
require(sf) # Combines sp, rgeos and rgdal functionality
require(cartography)
require(ggplot2)
require(ggrepel)
require(stringr)
require(magrittr)
```

# COnvert new GeoJSON files to SVG

This takes all geojson more recent than the most recent svg file and converts them

```{r}
basedir <- dirname(rstudioapi::getActiveDocumentContext()$path)
geodatas <- list.files(file.path(basedir,"geojson"),pattern="world_.*geojson") 
geodatas_fullpath <- list.files(file.path(basedir,"geojson"),pattern="world_.*geojson",full.names = TRUE) 
geodatas_mtime = file.mtime(geodatas_fullpath)
# i <- 14
for (i in 1:length(geodatas)) {
  geofile <- geodatas[i]
  geofilePure <- str_extract(geofile,"[^\\.]*")
  svg_files <- list.files(file.path(basedir,"svg"),pattern=geofilePure,full.names = TRUE)
  svg_mtime <- ifelse(length(svg_files) > 0, file.mtime(svg_files[1]), as.Date("2021-09-01") %>% as.POSIXct()) 
  if (geodatas_mtime[i] >= svg_mtime) { # update only SVGs more ancient than the current GeoJSON file
    year <- str_extract(geofilePure,"[^\\_]*$")
    geodata <- st_read(file.path(basedir,"geojson",geofile), quiet=TRUE)
    if(!"SUBJECTO" %in% colnames(geodata)) {
			geodata$SUBJECTO <- geodata$NAME
	  }
    geodata <- st_transform(geodata, "+proj=natearth2")
    # plot(st_geometry(geodata))
    # plot(geodata["NAME"])
    ggplot(data = geodata) + 
        geom_sf(aes(fill = SUBJECTO)) +
        # geom_sf_text(aes(label=NAME),size=0.5) +
        ggrepel::geom_text_repel(
          data = geodata,
          aes(label = NAME, geometry = geometry),
          stat = "sf_coordinates",
          min.segment.length = 0.2, # skip drawing segments shorter than this
          max.overlaps = 30,
          arrow = arrow(length = unit(0.05, 'cm'), type = 'closed'),
          segment.color = 'grey',
          size = 2
        ) +
        theme(legend.position="none") +
        labs(
          title=paste0("The World in ",year),
          subtitle= "Historical Boundaries of World Countries and Cultural Regions. (work in progress) https://github.com/aourednik/historical-basemaps",
          x = element_blank(), 
          y = element_blank(),
          caption = "André Ourednik & GitHub contributors, 2021"
        )
    ggsave(file.path(basedir,"svg",paste0(geofilePure,".svg")),width = 30, height=20) # needs svglite
    # tryCatch({
      # svg(file.path(basedir,"svg",paste0(geofilePure,".svg")),width = 30, 20)
      # typoLayer(
      #   x = geodata,
      #   var = "NAME",
      #   legend.pos = "n",
      #   legend.values.cex = 0.4
      # )
      # labelLayer(
      #   x = geodata, 
      #   txt = "NAME", 
      #   col= "black",
      #   cex=0.3,
      #   overlap=TRUE,
      #   show.lines = FALSE # connects lines to labels
      # )
      # layoutLayer(
      #   title = paste0("The World in ",year), 
      #   sources = "Historical Boundaries of World Countries and Cultural Regions. https://github.com/aourednik/historical-basemaps", 
      #   author = "GitHub contributors & André Ourednik, 2021",
      #   north = FALSE
      # )
      # dev.off()
    #}, error=function(e){print(paste(geofile,e))})
  }
}
```


# Documentation

* [cartographie avec R](https://rcarto.github.io/carto_avec_r/)
* [projections avec PROJ](https://proj.org/operations/projections/)
